apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartapigw.fullname" . }}
  labels:
    {{- include "chartapigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.servicetype "NodePort" }}
      nodePort: {{ .Values.port }}
  {{ end }}  
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "chartapigw.selectorLabels" . | nindent 4 }}
