apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartdotnetv2.fullname" . }}
  labels:
    {{- include "chartdotnetv2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.servicetype "NodePort" }}
      nodePort: {{ .Values.port }}
  {{ end }}  
      targetPort: http
      protocol: TCP
      name: http
  
  {{- if .Values.port2.enabled }}
    - port: {{ .Values.containerPort2 }}
      targetPort: {{ .Values.namePort2 }}
      protocol: TCP
      name: {{ .Values.namePort2 }}
  {{- end }}
  selector:
    {{- include "chartdotnetv2.selectorLabels" . | nindent 4 }}
